name: salts

dependencies:
  - python=3.8
  - antlr4-python3-runtime=4.8
  - numpy
  - matplotlib
  - transformers
  - tqdm
  - tensorboard
  - pip
  - pandas
  - seaborn
  - PyPDF2
  - pip:
    - -r requirements.txt