name: salts

dependencies:
  - python
  - antlr4-python3-runtime
  - pip
  - nltk
  - spacy
  - seaborn
  - hydra-core
  - tokenizers
  - datasets
  - numpy
  - matplotlib
  - transformers >=4.48.0
  - tqdm
  - tensorboard
  - pandas
  - setuptools
  - scikit-learn
  - Deprecated
  - tiktoken
  - blobfile
  - spacy
  - pip:
    - -r requirements.txt
