name: salts

dependencies:
  - python >=3.8,<=3.9.7
  - antlr4-python3-runtime=4.8
  - pip
  - seaborn
  - tokenizers
  - numpy=1.21.4
  - matplotlib=3.5.0
  - transformers=4.12.5
  - tqdm=4.62.3
  - tensorboard=2.7.0
  - pandas=1.3.4
  - setuptools <=59.5.0
  - pytorch=1.10.0
  - cudatoolkit=11.3
  - scikit-learn=1.0.2
  - pip:
    - -r requirements.txt
