name: salts

dependencies:
  - python>=3.8,<=3.9.7
  - antlr4-python3-runtime=4.8
  - numpy
  - matplotlib
  - transformers
  - tqdm
  - tensorboard
  - pip
  - pandas
  - seaborn
  - setuptools<=59.5.0
  - tokenizers
  - pip:
    - -r requirements.txt