name: salts

channels:
  - defaults
  - pytorch

dependencies:
  - python=3.8
  - numpy=1.21.2
  - matplotlib=3.4.3
  - transformers=4.10.3
  - tqdm=4.62.3
  - tensorboard=2.6.0
  - pytorch=1.9.0
  - pip
  - pip:
    - -r requirements.txt