defaults:
  - _self_
  - model: distilbert
  - tuning: dative_DO

hyperparameters:
  epochs: 70 # how many epochs should the model tune for
  masked: true # are the tuning inputs masked?
  lr: 0.001

hydra:
  run:
    dir: "./outputs/${tuning.name}/${model.friendly_name}-masked-${hyperparameters.masked}/${now:%Y-%m-%d_%H-%M-%S}"